src/main/java/com/baidu/hugegraph/structure/graph/Path.java
src/test/java/com/baidu/hugegraph/unit/BaseUnitTest.java
src/test/java/com/baidu/hugegraph/unit/RestResultTest.java

Change-Id: I4efac581998913c2664fbbc5d1fc91dfda6d36b2

HugeGraph-1334: Fixed bug that UnitTestSuite can't pass

---

src/main/java/com/baidu/hugegraph/driver/GraphManager.java

修复添加节点使用自定义数字id报错，代码请review，有什么问题随时联系我，感谢

Fix bug: Add Vertex Use useCustomizeNumberId to report error

---

pom.xml
src/main/java/com/baidu/hugegraph/api/job/RebuildAPI.java
src/main/java/com/baidu/hugegraph/api/schema/IndexLabelAPI.java
src/main/java/com/baidu/hugegraph/api/task/TaskAPI.java
src/main/java/com/baidu/hugegraph/driver/GremlinManager.java
src/main/java/com/baidu/hugegraph/driver/HugeClient.java
src/main/java/com/baidu/hugegraph/driver/JobManager.java
src/main/java/com/baidu/hugegraph/driver/SchemaManager.java
src/main/java/com/baidu/hugegraph/driver/TaskManager.java
src/main/java/com/baidu/hugegraph/structure/Task.java
src/main/java/com/baidu/hugegraph/structure/schema/IndexLabel.java
src/main/java/com/baidu/hugegraph/util/TaskCache.java
src/test/java/com/baidu/hugegraph/api/BaseApiTest.java
src/test/java/com/baidu/hugegraph/api/EdgeLabelApiTest.java
src/test/java/com/baidu/hugegraph/api/IndexLabelApiTest.java
src/test/java/com/baidu/hugegraph/functional/BaseFuncTest.java
src/test/java/com/baidu/hugegraph/functional/EdgeLabelTest.java
src/test/java/com/baidu/hugegraph/functional/IndexLabelTest.java
src/test/java/com/baidu/hugegraph/functional/VertexLabelTest.java

fixed: #7 
Change-Id: I0fc8a6414d140ea4c31b231c59cc560031f52ed2

Adapt to server's index-create API returning task-id and indexLabel 

---

pom.xml
src/main/java/com/baidu/hugegraph/api/graphs/GraphsAPI.java
src/main/java/com/baidu/hugegraph/driver/GraphsManager.java
src/main/java/com/baidu/hugegraph/driver/HugeClient.java
src/main/java/com/baidu/hugegraph/structure/SchemaElement.java
src/main/java/com/baidu/hugegraph/structure/constant/GraphMode.java
src/main/java/com/baidu/hugegraph/structure/schema/IndexLabel.java
src/test/java/com/baidu/hugegraph/BaseClientTest.java
src/test/java/com/baidu/hugegraph/api/ApiTestSuite.java
src/test/java/com/baidu/hugegraph/api/BaseApiTest.java
src/test/java/com/baidu/hugegraph/api/RestoreApiTest.java
src/test/java/com/baidu/hugegraph/api/TaskApiTest.java
src/test/java/com/baidu/hugegraph/functional/EdgeLabelTest.java
src/test/java/com/baidu/hugegraph/functional/GraphModeTest.java
src/test/java/com/baidu/hugegraph/functional/IndexLabelTest.java
src/test/java/com/baidu/hugegraph/functional/PropertyKeyTest.java
src/test/java/com/baidu/hugegraph/functional/VertexLabelTest.java
src/test/java/com/baidu/hugegraph/unit/RestResultTest.java

Change-Id: Ib2c3b145934f75e97b454ce47f88279566e1fc73

Add restore mode api support

---

pom.xml
src/main/java/com/baidu/hugegraph/annotation/UnimplementedFeature.java
src/main/java/com/baidu/hugegraph/api/graph/GraphAPI.java
src/main/java/com/baidu/hugegraph/driver/GraphManager.java
src/main/java/com/baidu/hugegraph/driver/SchemaManager.java
src/main/java/com/baidu/hugegraph/exception/NotSupportException.java
src/main/java/com/baidu/hugegraph/structure/graph/GraphIterator.java
src/test/java/com/baidu/hugegraph/functional/FuncTestSuite.java
src/test/java/com/baidu/hugegraph/functional/GraphManagerTest.java

Fix #13
Change-Id: I98371718af0b2f73ec687f4ba3eb5a42ae4954ea

Fix graph iterate vertices/edges in page error

---

pom.xml
src/main/java/com/baidu/hugegraph/structure/GraphElement.java
src/main/java/com/baidu/hugegraph/structure/constant/IdStrategy.java

Fix #25
Change-Id: If010f366abc0003251f54f085035e0d7da2fd328

Should validate date type instead of timestamp when add property

---

pom.xml
src/main/java/com/baidu/hugegraph/api/traverser/CrosspointsAPI.java
src/main/java/com/baidu/hugegraph/api/traverser/KneighborAPI.java
src/main/java/com/baidu/hugegraph/api/traverser/KoutAPI.java
src/main/java/com/baidu/hugegraph/api/traverser/PathsAPI.java
src/main/java/com/baidu/hugegraph/api/traverser/ShortestPathAPI.java
src/main/java/com/baidu/hugegraph/driver/HugeClient.java

Change-Id: I58c16e0e786797a202f5284af19d0a580b5d0557

keep depth and degree consistent for traverser api

---

.travis.yml
pom.xml

Change-Id: I3368279fd832157db8f4807b3e383118e0b1596b

Replace cobertura with jacoco to statistic code coverage

---

pom.xml
src/main/java/com/baidu/hugegraph/driver/GraphManager.java
src/main/java/com/baidu/hugegraph/example/BatchExample.java
src/main/java/com/baidu/hugegraph/structure/GraphElement.java
src/main/java/com/baidu/hugegraph/structure/graph/Edge.java
src/main/java/com/baidu/hugegraph/structure/graph/Graph.java
src/main/java/com/baidu/hugegraph/structure/graph/Vertex.java
src/test/java/com/baidu/hugegraph/BaseClientTest.java
src/test/java/com/baidu/hugegraph/api/EdgeApiTest.java
src/test/java/com/baidu/hugegraph/functional/BatchInsertTest.java
src/test/java/com/baidu/hugegraph/functional/EdgeTest.java
src/test/java/com/baidu/hugegraph/functional/FuncTestSuite.java
src/test/java/com/baidu/hugegraph/testutil/Utils.java
src/test/java/com/baidu/hugegraph/unit/PathSerializerTest.java
src/test/java/com/baidu/hugegraph/unit/RestResultTest.java

Change-Id: I6ab984d5840dc641bc1162937c9bd01081b31224

Let Edge reference Vertex to make batch inser friendly

---

pom.xml
src/main/java/com/baidu/hugegraph/api/traverser/EdgesAPI.java
src/main/java/com/baidu/hugegraph/api/traverser/VerticesAPI.java
src/main/java/com/baidu/hugegraph/driver/HugeClient.java
src/main/java/com/baidu/hugegraph/driver/TraverserManager.java
src/main/java/com/baidu/hugegraph/structure/constant/Traverser.java
src/test/java/com/baidu/hugegraph/api/TraverserApiTest.java

implemented: #360
Change-Id: I6f92748fff7da8de337cc02f9a1962949301a36b

Support paging for scan api

---

src/main/java/com/baidu/hugegraph/driver/TraverserManager.java

implemented: #45 
Change-Id: Ib3b6d2476756578e52c42982a5a5da11698b59a8

keep traverser methods args consistent with server

---

pom.xml
src/main/java/com/baidu/hugegraph/driver/TraverserManager.java
src/main/java/com/baidu/hugegraph/structure/graph/GraphIterator.java
src/test/java/com/baidu/hugegraph/BaseClientTest.java
src/test/java/com/baidu/hugegraph/functional/FuncTestSuite.java
src/test/java/com/baidu/hugegraph/functional/TraverserManagerTest.java

Change-Id: Ic64ca086bc6b1743b9dbccd53075512000d982ee

Add method to iterate vertices/edges with shard in page

---

pom.xml
src/main/java/com/baidu/hugegraph/client/RestClient.java
src/main/java/com/baidu/hugegraph/driver/GremlinManager.java
src/main/java/com/baidu/hugegraph/driver/HugeClient.java
src/main/java/com/baidu/hugegraph/structure/GraphElement.java
src/main/java/com/baidu/hugegraph/structure/constant/GraphAttachable.java
src/main/java/com/baidu/hugegraph/structure/graph/Path.java
src/main/java/com/baidu/hugegraph/structure/gremlin/Response.java
src/main/java/com/baidu/hugegraph/structure/gremlin/ResultSet.java
src/test/java/com/baidu/hugegraph/api/GremlinApiTest.java
src/test/java/com/baidu/hugegraph/unit/BaseUnitTest.java
src/test/java/com/baidu/hugegraph/unit/RestResultTest.java

Change-Id: I912eace9eb3f8fc71590ca2e453b84803def445c

Support gremlin result attach GraphManager

---

pom.xml
src/main/java/com/baidu/hugegraph/driver/HugeClient.java
src/main/java/com/baidu/hugegraph/example/BatchExample.java
src/main/java/com/baidu/hugegraph/example/SingleExample.java

Change-Id: I3594610f18781159ff3f3f079dc9c5208a462e30

Improve connection params in RestClient

---

src/main/java/com/baidu/hugegraph/example/BatchExample.java
src/main/java/com/baidu/hugegraph/example/SingleExample.java
src/test/java/com/baidu/hugegraph/BaseClientTest.java
src/test/java/com/baidu/hugegraph/api/CustomizedPathsApiTest.java
src/test/java/com/baidu/hugegraph/api/EdgeApiTest.java
src/test/java/com/baidu/hugegraph/api/TraverserApiTest.java
src/test/java/com/baidu/hugegraph/api/VertexApiTest.java
src/test/java/com/baidu/hugegraph/functional/EdgeTest.java
src/test/java/com/baidu/hugegraph/functional/VertexTest.java
src/test/java/com/baidu/hugegraph/testutil/Utils.java
src/test/java/com/baidu/hugegraph/unit/PathSerializerTest.java
src/test/java/com/baidu/hugegraph/unit/RestResultTest.java

Change-Id: Ide30a00770c2a2904f666560798779e9b50a507a

Let date property asDate in tests

---

pom.xml
src/main/java/com/baidu/hugegraph/driver/HugeClient.java
src/test/java/com/baidu/hugegraph/api/BaseApiTest.java
src/test/java/com/baidu/hugegraph/api/GremlinApiTest.java

Change-Id: I42d742c756c29a888253569c0359a9d70cd29d25

Adapt HugeGremlinException and add some tests

---

src/main/java/com/baidu/hugegraph/driver/HugeClient.java
src/main/java/com/baidu/hugegraph/structure/constant/IndexType.java
src/main/java/com/baidu/hugegraph/structure/schema/IndexLabel.java
src/test/java/com/baidu/hugegraph/api/CustomizedPathsApiTest.java
src/test/java/com/baidu/hugegraph/api/EdgeApiTest.java
src/test/java/com/baidu/hugegraph/api/EdgeLabelApiTest.java
src/test/java/com/baidu/hugegraph/api/GremlinApiTest.java
src/test/java/com/baidu/hugegraph/api/IndexLabelApiTest.java
src/test/java/com/baidu/hugegraph/api/NeighborRankApiTest.java
src/test/java/com/baidu/hugegraph/api/RingsRaysApiTest.java
src/test/java/com/baidu/hugegraph/api/ShortestPathApiTest.java
src/test/java/com/baidu/hugegraph/api/TraverserApiTest.java

Change-Id: I1e316851b90e6d7ad625e83b34f4258ea841576e

support shard-index

---

.travis.yml
pom.xml
src/main/java/com/baidu/hugegraph/structure/constant/IdStrategy.java
src/main/java/com/baidu/hugegraph/structure/schema/EdgeLabel.java
src/main/java/com/baidu/hugegraph/structure/schema/IndexLabel.java
src/main/java/com/baidu/hugegraph/structure/schema/PropertyKey.java
src/main/java/com/baidu/hugegraph/structure/schema/VertexLabel.java
src/test/java/com/baidu/hugegraph/api/EdgeLabelApiTest.java
src/test/java/com/baidu/hugegraph/api/IndexLabelApiTest.java
src/test/java/com/baidu/hugegraph/api/PropertyKeyApiTest.java
src/test/java/com/baidu/hugegraph/api/VertexLabelApiTest.java

Change-Id: Ie86f8a7753bf9e0cde92abf7ac3d7cf72d95769b

Support uuid idstrategy

---

pom.xml
src/main/java/com/baidu/hugegraph/driver/HugeClient.java
src/main/java/com/baidu/hugegraph/structure/constant/IndexType.java
src/main/java/com/baidu/hugegraph/structure/schema/IndexLabel.java
src/test/java/com/baidu/hugegraph/api/IndexLabelApiTest.java

implemented: #633
Change-Id: I226e73eb4d06e901fe4aa4fc38f6480a78a4767d

support unique index

---

pom.xml
src/main/java/com/baidu/hugegraph/api/graph/GraphAPI.java
src/main/java/com/baidu/hugegraph/api/job/GremlinJobAPI.java
src/main/java/com/baidu/hugegraph/api/schema/VertexLabelAPI.java
src/main/java/com/baidu/hugegraph/api/task/TaskAPI.java
src/main/java/com/baidu/hugegraph/api/traverser/RingsAPI.java
src/main/java/com/baidu/hugegraph/api/traverser/structure/Ranks.java
src/main/java/com/baidu/hugegraph/driver/HugeClient.java
src/main/java/com/baidu/hugegraph/structure/constant/IdStrategy.java
src/main/java/com/baidu/hugegraph/structure/schema/VertexLabel.java
src/main/java/com/baidu/hugegraph/util/TaskCache.java
src/test/java/com/baidu/hugegraph/BaseClientTest.java
src/test/java/com/baidu/hugegraph/api/VertexApiTest.java
src/test/java/com/baidu/hugegraph/api/VertexLabelApiTest.java

Change-Id: I215dd562322b1947fbb212b468e3ce67cdf615f3

Adapt the serialization of uuid

---

pom.xml
src/main/java/com/baidu/hugegraph/api/schema/PropertyKeyAPI.java
src/main/java/com/baidu/hugegraph/client/RestClient.java
src/main/java/com/baidu/hugegraph/driver/HugeClient.java
src/main/java/com/baidu/hugegraph/structure/constant/AggregateType.java
src/main/java/com/baidu/hugegraph/structure/schema/PropertyKey.java
src/test/java/com/baidu/hugegraph/api/PropertyKeyApiTest.java
src/test/java/com/baidu/hugegraph/unit/PropertyKeyTest.java
src/test/java/com/baidu/hugegraph/unit/UnitTestSuite.java

implemented: #691
Change-Id: I861927cfa48407759785534b4045a55e73ef7a00

adapt to update_props(aggregate)

---

pom.xml
src/main/java/com/baidu/hugegraph/api/schema/EdgeLabelAPI.java
src/main/java/com/baidu/hugegraph/api/schema/IndexLabelAPI.java
src/main/java/com/baidu/hugegraph/api/schema/PropertyKeyAPI.java
src/main/java/com/baidu/hugegraph/api/schema/VertexLabelAPI.java
src/main/java/com/baidu/hugegraph/driver/HugeClient.java
src/main/java/com/baidu/hugegraph/driver/SchemaManager.java
src/main/java/com/baidu/hugegraph/structure/graph/Edge.java
src/main/java/com/baidu/hugegraph/structure/schema/EdgeLabel.java
src/main/java/com/baidu/hugegraph/structure/schema/IndexLabel.java
src/test/java/com/baidu/hugegraph/BaseClientTest.java
src/test/java/com/baidu/hugegraph/api/EdgeLabelApiTest.java
src/test/java/com/baidu/hugegraph/api/IndexLabelApiTest.java
src/test/java/com/baidu/hugegraph/api/PropertyKeyApiTest.java
src/test/java/com/baidu/hugegraph/api/VertexLabelApiTest.java
src/test/java/com/baidu/hugegraph/functional/EdgeLabelTest.java
src/test/java/com/baidu/hugegraph/functional/EdgeTest.java
src/test/java/com/baidu/hugegraph/functional/IndexLabelTest.java
src/test/java/com/baidu/hugegraph/functional/PropertyKeyTest.java
src/test/java/com/baidu/hugegraph/functional/VertexLabelTest.java

Change-Id: Ie2a50982169323d9cf4b30a8edce5ab04e85cf0d

Support get schema by names

---

pom.xml
src/main/java/com/baidu/hugegraph/api/traverser/FusiformSimilarityAPI.java
src/main/java/com/baidu/hugegraph/api/traverser/structure/FusiformSimilarity.java
src/main/java/com/baidu/hugegraph/api/traverser/structure/FusiformSimilarityRequest.java
src/main/java/com/baidu/hugegraph/driver/HugeClient.java
src/main/java/com/baidu/hugegraph/driver/TraverserManager.java
src/main/java/com/baidu/hugegraph/structure/Element.java
src/main/java/com/baidu/hugegraph/structure/SchemaElement.java
src/test/java/com/baidu/hugegraph/api/BaseApiTest.java
src/test/java/com/baidu/hugegraph/api/FusiformSimilarityApiTest.java
src/test/java/com/baidu/hugegraph/functional/EdgeLabelTest.java
src/test/java/com/baidu/hugegraph/functional/PropertyKeyTest.java
src/test/java/com/baidu/hugegraph/functional/VertexLabelTest.java

implemented: #670
Change-Id: Iffd09599e754bc70189ab0b3f5378ce1cebcfb79

support fusiform similarity API

---

pom.xml
src/main/java/com/baidu/hugegraph/api/schema/IndexLabelAPI.java
src/main/java/com/baidu/hugegraph/driver/HugeClient.java
src/main/java/com/baidu/hugegraph/driver/SchemaManager.java
src/main/java/com/baidu/hugegraph/structure/schema/IndexLabel.java
src/test/java/com/baidu/hugegraph/api/EdgeLabelApiTest.java
src/test/java/com/baidu/hugegraph/api/IndexLabelApiTest.java
src/test/java/com/baidu/hugegraph/api/PropertyKeyApiTest.java
src/test/java/com/baidu/hugegraph/api/VertexLabelApiTest.java
src/test/java/com/baidu/hugegraph/functional/EdgeLabelTest.java
src/test/java/com/baidu/hugegraph/functional/FuncTestSuite.java
src/test/java/com/baidu/hugegraph/functional/IndexLabelTest.java
src/test/java/com/baidu/hugegraph/functional/PropertyKeyTest.java
src/test/java/com/baidu/hugegraph/functional/VertexLabelTest.java
src/test/java/com/baidu/hugegraph/functional/VertexTest.java

Change-Id: I7406672b64c8b7b854db4e9b6b31e331962cd622

Adapt record create time when create schema

---

src/main/java/com/baidu/hugegraph/api/gremlin/GremlinRequest.java

Fix GremlinRequest binding parameter types

---

pom.xml
src/main/java/com/baidu/hugegraph/api/schema/IndexLabelAPI.java
src/main/java/com/baidu/hugegraph/example/MovieExample.java
src/main/java/com/baidu/hugegraph/structure/schema/IndexLabel.java
src/main/java/com/baidu/hugegraph/version/ClientVersion.java
src/test/java/com/baidu/hugegraph/api/BaseApiTest.java
src/test/java/com/baidu/hugegraph/api/IndexLabelApiTest.java
src/test/java/com/baidu/hugegraph/unit/IndexLabelTest.java
src/test/java/com/baidu/hugegraph/unit/UnitTestSuite.java

Change-Id: Iee17fe908a4bfc1f79b77cc1869b28ef5710bb36

Adapt server doesn't support indexlabel userdata and upgrade dependency version

---

pom.xml
src/main/java/com/baidu/hugegraph/driver/HugeClient.java

Change-Id: I2f49afcee9b0f2cd6b9580139fc12accbb979a3a

Fix client initManagers failed not close conn pool

---

pom.xml
src/main/java/com/baidu/hugegraph/api/graph/EdgeAPI.java
src/main/java/com/baidu/hugegraph/api/graph/VertexAPI.java
src/main/java/com/baidu/hugegraph/driver/GraphManager.java
src/test/java/com/baidu/hugegraph/BaseClientTest.java
src/test/java/com/baidu/hugegraph/api/BatchUpdateElementApiTest.java
src/test/java/com/baidu/hugegraph/api/VertexApiTest.java
src/test/java/com/baidu/hugegraph/functional/EdgeTest.java
src/test/java/com/baidu/hugegraph/functional/VertexTest.java

adapt range query rest api 

---

pom.xml
src/main/java/com/baidu/hugegraph/driver/HugeClient.java
src/test/java/com/baidu/hugegraph/api/EdgeApiTest.java
src/test/java/com/baidu/hugegraph/api/EdgeLabelApiTest.java
src/test/java/com/baidu/hugegraph/api/IndexLabelApiTest.java
src/test/java/com/baidu/hugegraph/api/PropertyKeyApiTest.java
src/test/java/com/baidu/hugegraph/api/TraverserApiTest.java
src/test/java/com/baidu/hugegraph/api/VertexApiTest.java
src/test/java/com/baidu/hugegraph/api/VertexLabelApiTest.java
src/test/java/com/baidu/hugegraph/functional/EdgeLabelTest.java
src/test/java/com/baidu/hugegraph/functional/EdgeTest.java
src/test/java/com/baidu/hugegraph/functional/IndexLabelTest.java
src/test/java/com/baidu/hugegraph/functional/PropertyKeyTest.java
src/test/java/com/baidu/hugegraph/functional/VertexLabelTest.java
src/test/java/com/baidu/hugegraph/functional/VertexTest.java
src/test/java/com/baidu/hugegraph/testutil/Utils.java

Change-Id: I5cca04aa9f27da074e67b2f2bb128290ed4343a3

adapt client to date prop with String format

---

pom.xml
src/main/java/com/baidu/hugegraph/api/schema/EdgeLabelAPI.java
src/main/java/com/baidu/hugegraph/api/schema/VertexLabelAPI.java
src/main/java/com/baidu/hugegraph/structure/SchemaElement.java
src/main/java/com/baidu/hugegraph/structure/schema/EdgeLabel.java
src/main/java/com/baidu/hugegraph/structure/schema/IndexLabel.java
src/main/java/com/baidu/hugegraph/structure/schema/PropertyKey.java
src/main/java/com/baidu/hugegraph/structure/schema/SchemaLabel.java
src/main/java/com/baidu/hugegraph/structure/schema/VertexLabel.java
src/test/java/com/baidu/hugegraph/api/EdgeApiTest.java
src/test/java/com/baidu/hugegraph/api/EdgeLabelApiTest.java
src/test/java/com/baidu/hugegraph/api/VertexApiTest.java
src/test/java/com/baidu/hugegraph/api/VertexLabelApiTest.java
src/test/java/com/baidu/hugegraph/testutil/Utils.java
src/test/java/com/baidu/hugegraph/unit/IndexLabelTest.java

Change-Id: If67c51e31053be1da1da1006af3e91abd770e826

support vertexlabel/edgelabel ttl

---

src/main/java/com/baidu/hugegraph/driver/GraphManager.java
src/main/java/com/baidu/hugegraph/structure/graph/Vertex.java
src/test/java/com/baidu/hugegraph/functional/EdgeTest.java
src/test/java/com/baidu/hugegraph/functional/VertexTest.java

Change-Id: If204d5e12f30262dab1a7a99bd13744972607971

Support to create vertex/edge with map properties

---

pom.xml
src/main/java/com/baidu/hugegraph/api/schema/IndexLabelAPI.java
src/main/java/com/baidu/hugegraph/driver/HugeClient.java
src/main/java/com/baidu/hugegraph/example/BatchExample.java
src/main/java/com/baidu/hugegraph/example/MovieExample.java
src/main/java/com/baidu/hugegraph/example/SingleExample.java
src/main/java/com/baidu/hugegraph/structure/Task.java
src/main/java/com/baidu/hugegraph/structure/graph/Edge.java
src/main/java/com/baidu/hugegraph/structure/schema/IndexLabel.java
src/test/java/com/baidu/hugegraph/api/IndexLabelApiTest.java
src/test/java/com/baidu/hugegraph/api/TaskApiTest.java
src/test/java/com/baidu/hugegraph/api/traverser/AllShortestPathsApiTest.java
src/test/java/com/baidu/hugegraph/api/traverser/ShortestPathApiTest.java
src/test/java/com/baidu/hugegraph/unit/IndexLabelTest.java

Change-Id: Ib9f309e1eb8fb2814affe156a6f1be5fa203e86b

add rebuild(boolean) for indexlabel builder

---

src/main/java/com/baidu/hugegraph/api/schema/EdgeLabelAPI.java
src/main/java/com/baidu/hugegraph/api/schema/IndexLabelAPI.java
src/main/java/com/baidu/hugegraph/api/schema/PropertyKeyAPI.java
src/main/java/com/baidu/hugegraph/api/schema/SchemaAPI.java
src/main/java/com/baidu/hugegraph/api/schema/VertexLabelAPI.java
src/test/java/com/baidu/hugegraph/api/IndexLabelApiTest.java

Change-Id: I9864be88067e38490f34296f96697f96e5b24266

unify api check for create/update of schema

---

src/main/java/com/baidu/hugegraph/structure/schema/IndexLabel.java
src/test/java/com/baidu/hugegraph/unit/IndexLabelTest.java

Change-Id: I59360171e284e892ceb1f824ac6e6ebde95a8aec

fix index label serialize with properties field

---

pom.xml
src/main/java/com/baidu/hugegraph/structure/constant/GraphMode.java

Change-Id: Ifc24889fc5cf5cf5750433c7c50c099194d6af54

Define loading mode to speed up when loading data

---

pom.xml
src/main/java/com/baidu/hugegraph/version/ClientVersion.java

Change-Id: Ib9c111363745ec02dd799ebae259363f78b3bd90

Upgrade version to 1.9.0 for release

---

assembly/travis/install-hugegraph.sh
pom.xml
src/main/java/com/baidu/hugegraph/client/RestClient.java
src/main/java/com/baidu/hugegraph/driver/HugeClient.java
src/main/java/com/baidu/hugegraph/driver/HugeClientBuilder.java
src/test/java/com/baidu/hugegraph/functional/HugeClientHttpsTest.java

Change-Id: Ied484f2121a731e312868b6fcd89b790b8465dd2

adapt to https+auth

---

src/test/java/com/baidu/hugegraph/api/traverser/SingleSourceShortestPathApiTest.java

Change-Id: Ib8fce033726823184dd4900756a3f8ce2537bb6b

fix sssp test bug

---

pom.xml
src/main/java/com/baidu/hugegraph/structure/auth/HugeResourceType.java
src/test/java/com/baidu/hugegraph/api/traverser/KneighborApiTest.java
src/test/java/com/baidu/hugegraph/api/traverser/KoutApiTest.java

Change-Id: Ifee0e06acfbe3390720f874e9e5ce88356d06060

auth: add resource metrics_read

---

src/main/java/com/baidu/hugegraph/structure/auth/HugeResourceType.java

Change-Id: I69c9216755fee88baf3d873ef83481bcb7ed94c4

auth: add resource schema

---

pom.xml

Change-Id: Ib428056743bdf847e5d3110755912282c8b0dfdc

Upgrade version to 1.9.3 and adapt common 1.8.4

---

pom.xml
src/test/java/com/baidu/hugegraph/api/auth/UserApiTest.java

Change-Id: I3d1744a6fb110a36337678fd89b73c809e6ab98b

Fix senstive mail address

---

pom.xml
src/main/java/com/baidu/hugegraph/structure/graph/Edge.java
src/main/java/com/baidu/hugegraph/util/IdUtil.java
src/main/java/com/baidu/hugegraph/util/SplicingIdGenerator.java
src/test/java/com/baidu/hugegraph/BaseClientTest.java
src/test/java/com/baidu/hugegraph/functional/EdgeTest.java
src/test/java/com/baidu/hugegraph/unit/IdUtilTest.java
src/test/java/com/baidu/hugegraph/unit/SplicingIdGeneratorTest.java
src/test/java/com/baidu/hugegraph/unit/UnitTestSuite.java

* name is concated by sort values
Change-Id: I2eaa7ecd0e2d6dbd587063b466908b554f8cbbcd

Add name for Edge

---

.github/workflows/ci.yml
assembly/travis/install-hugegraph-from-source.sh
src/main/java/com/baidu/hugegraph/driver/HugeClient.java
src/test/java/com/baidu/hugegraph/api/traverser/PersonalRankApiTest.java

Change-Id: I905abf4ca684f265290983021a91bef934ba0fcb

chore: use github action to run ci

---

.github/workflows/ci.yml
src/main/java/com/baidu/hugegraph/api/schema/IndexLabelAPI.java
src/main/java/com/baidu/hugegraph/api/schema/PropertyKeyAPI.java
src/main/java/com/baidu/hugegraph/api/task/TaskAPI.java
src/main/java/com/baidu/hugegraph/driver/HugeClient.java
src/main/java/com/baidu/hugegraph/driver/SchemaManager.java
src/main/java/com/baidu/hugegraph/structure/constant/ReadFrequency.java
src/main/java/com/baidu/hugegraph/structure/constant/WriteType.java
src/main/java/com/baidu/hugegraph/structure/schema/IndexLabel.java
src/main/java/com/baidu/hugegraph/structure/schema/PropertyKey.java
src/test/java/com/baidu/hugegraph/api/BaseApiTest.java
src/test/java/com/baidu/hugegraph/api/IndexLabelApiTest.java
src/test/java/com/baidu/hugegraph/api/PropertyKeyApiTest.java
src/test/java/com/baidu/hugegraph/api/VertexApiTest.java
src/test/java/com/baidu/hugegraph/functional/IndexLabelTest.java
src/test/java/com/baidu/hugegraph/functional/PropertyKeyTest.java
src/test/java/com/baidu/hugegraph/testutil/Utils.java
src/test/java/com/baidu/hugegraph/unit/PropertyKeyTest.java

Change-Id: I86f9cb0307f4dd615b9672667e56bb906f9086a7

adapt for olap writeback

---

.github/workflows/ci.yml
src/main/java/com/baidu/hugegraph/api/schema/EdgeLabelAPI.java
src/main/java/com/baidu/hugegraph/api/schema/IndexLabelAPI.java
src/main/java/com/baidu/hugegraph/api/schema/PropertyKeyAPI.java
src/main/java/com/baidu/hugegraph/api/schema/SchemaAPI.java
src/main/java/com/baidu/hugegraph/api/schema/SchemaElementAPI.java
src/main/java/com/baidu/hugegraph/api/schema/VertexLabelAPI.java
src/main/java/com/baidu/hugegraph/driver/HugeClient.java
src/main/java/com/baidu/hugegraph/driver/SchemaManager.java
src/test/java/com/baidu/hugegraph/api/ApiTestSuite.java
src/test/java/com/baidu/hugegraph/api/BaseApiTest.java
src/test/java/com/baidu/hugegraph/api/SchemaApiTest.java
src/test/java/com/baidu/hugegraph/functional/FuncTestSuite.java
src/test/java/com/baidu/hugegraph/functional/SchemaTest.java

Change-Id: Ie6e10043c9f32f1c1be5f6c44a9a9505be37a7ff

adapt to schema get api

---

.github/workflows/ci.yml
assembly/travis/install-hugegraph-from-source.sh
pom.xml
src/main/java/com/baidu/hugegraph/version/ClientVersion.java
src/test/java/com/baidu/hugegraph/api/BatchUpdateElementApiTest.java
src/test/java/com/baidu/hugegraph/api/auth/ProjectApiTest.java
src/test/java/com/baidu/hugegraph/api/traverser/PersonalRankApiTest.java
src/test/java/com/baidu/hugegraph/functional/BaseFuncTest.java
src/test/java/com/baidu/hugegraph/functional/BatchInsertTest.java
src/test/java/com/baidu/hugegraph/functional/FuncTestSuite.java
src/test/java/com/baidu/hugegraph/functional/HugeClientHttpsTest.java
src/test/java/com/baidu/hugegraph/functional/MetricsManagerTest.java

maybe need also change commit id in shell
also fix #136

refact: adopt personal pagerank & update ubuntu 20.04 & common 2.0.1

---

src/main/java/com/baidu/hugegraph/structure/constant/Traverser.java
src/test/java/com/baidu/hugegraph/api/traverser/PersonalRankApiTest.java

change master **commit id** later (no need in this pr)

refact: unify max depth
